# SPDX-License-Identifier: LGPL-3.0-only
# Copyright (c) 2026 ShmidtS

"""
Configuration module for the rotator library.

Exports centralized defaults used via the package path.
"""

from .defaults import (
    # Rotation & Selection
    DEFAULT_ROTATION_MODE,
    DEFAULT_ROTATION_TOLERANCE,
    DEFAULT_MAX_RETRIES,
    DEFAULT_GLOBAL_TIMEOUT,
    # Tier & Priority
    DEFAULT_TIER_PRIORITY,
    DEFAULT_SEQUENTIAL_FALLBACK_MULTIPLIER,
    # Fair Cycle Rotation
    DEFAULT_FAIR_CYCLE_ENABLED,
    DEFAULT_FAIR_CYCLE_TRACKING_MODE,
    DEFAULT_FAIR_CYCLE_CROSS_TIER,
    DEFAULT_FAIR_CYCLE_DURATION,
    DEFAULT_EXHAUSTION_COOLDOWN_THRESHOLD,
    # Custom Caps
    DEFAULT_CUSTOM_CAP_COOLDOWN_MODE,
    DEFAULT_CUSTOM_CAP_COOLDOWN_VALUE,
    # Cooldown & Backoff
    COOLDOWN_BACKOFF_TIERS,
    COOLDOWN_BACKOFF_MAX,
    COOLDOWN_AUTH_ERROR,
    COOLDOWN_TRANSIENT_ERROR,
    COOLDOWN_RATE_LIMIT_DEFAULT,
    # Circuit Breaker
    CIRCUIT_BREAKER_PROVIDER_OVERRIDES,
    HTTP_COMPRESSION_THRESHOLD,
    HTTP_GZIP_MAX_WORKERS,
    HTTP_KEEPALIVE_EXPIRY,
    HTTP_MAX_CONNECTIONS_POSIX,
    HTTP_MAX_CONNECTIONS_WINDOWS,
    HTTP_MAX_KEEPALIVE_POSIX,
    HTTP_MAX_KEEPALIVE_WINDOWS,
    HTTP_SSL_VERIFY_DEFAULT,
    HTTP_STREAMING_KEEPALIVE_EXPIRY,
    HTTP_STREAMING_MAX_CONNECTIONS_POSIX,
    HTTP_STREAMING_MAX_CONNECTIONS_WINDOWS,
    HTTP_STREAMING_MAX_KEEPALIVE_POSIX,
    HTTP_STREAMING_MAX_KEEPALIVE_WINDOWS,
    HTTP_WARMUP_CONNECTIONS,
    HTTP_WARMUP_HOST_LIMIT,
    RETRY_SAME_KEY_MAX_WAIT,
    # Provider Backoff
    KILOCODE_BACKOFF_BASE,
    KILOCODE_MAX_BACKOFF,
    INCEPTION_BACKOFF_BASE,
    INCEPTION_MAX_BACKOFF,
    # Proxy Providers
    PROXY_PROVIDERS,
    # Background Refresher
    OAUTH_REFRESH_INTERVAL,
    # Batch Persistence
    USAGE_BATCH_PERSISTENCE,
    # DNS Resolver
    HTTP_DNS_RESOLVER,
    # SSL
    SSL_FORCE_TLS12,
    HTTP_SSL_VERIFY_HOSTS,
    # LiteLLM Patches
    PATCH_LITELLM_FINISH_REASON,
    SUPPRESS_LITELLM_SERIALIZATION_WARNINGS,
    # HTTP Client Misc
    HTTP2_ENABLED,
)
from .defaults import env_bool, env_float, env_int

__all__ = [
    # Rotation & Selection
    "DEFAULT_ROTATION_MODE",
    "DEFAULT_ROTATION_TOLERANCE",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_GLOBAL_TIMEOUT",
    # Tier & Priority
    "DEFAULT_TIER_PRIORITY",
    "DEFAULT_SEQUENTIAL_FALLBACK_MULTIPLIER",
    # Fair Cycle Rotation
    "DEFAULT_FAIR_CYCLE_ENABLED",
    "DEFAULT_FAIR_CYCLE_TRACKING_MODE",
    "DEFAULT_FAIR_CYCLE_CROSS_TIER",
    "DEFAULT_FAIR_CYCLE_DURATION",
    "DEFAULT_EXHAUSTION_COOLDOWN_THRESHOLD",
    # Custom Caps
    "DEFAULT_CUSTOM_CAP_COOLDOWN_MODE",
    "DEFAULT_CUSTOM_CAP_COOLDOWN_VALUE",
    # Cooldown & Backoff
    "COOLDOWN_BACKOFF_TIERS",
    "COOLDOWN_BACKOFF_MAX",
    "COOLDOWN_AUTH_ERROR",
    "COOLDOWN_TRANSIENT_ERROR",
    "COOLDOWN_RATE_LIMIT_DEFAULT",
    # Circuit Breaker
    "CIRCUIT_BREAKER_PROVIDER_OVERRIDES",
    # HTTP client pool
    "HTTP_COMPRESSION_THRESHOLD",
    "HTTP_GZIP_MAX_WORKERS",
    "HTTP_KEEPALIVE_EXPIRY",
    "HTTP_MAX_CONNECTIONS_POSIX",
    "HTTP_MAX_CONNECTIONS_WINDOWS",
    "HTTP_MAX_KEEPALIVE_POSIX",
    "HTTP_MAX_KEEPALIVE_WINDOWS",
    "HTTP_SSL_VERIFY_DEFAULT",
    "HTTP_STREAMING_KEEPALIVE_EXPIRY",
    "HTTP_STREAMING_MAX_CONNECTIONS_POSIX",
    "HTTP_STREAMING_MAX_CONNECTIONS_WINDOWS",
    "HTTP_STREAMING_MAX_KEEPALIVE_POSIX",
    "HTTP_STREAMING_MAX_KEEPALIVE_WINDOWS",
    "HTTP_WARMUP_CONNECTIONS",
    "HTTP_WARMUP_HOST_LIMIT",
    "RETRY_SAME_KEY_MAX_WAIT",
    # Provider Backoff
    "KILOCODE_BACKOFF_BASE",
    "KILOCODE_MAX_BACKOFF",
    "INCEPTION_BACKOFF_BASE",
    "INCEPTION_MAX_BACKOFF",
    # Proxy Providers
    "PROXY_PROVIDERS",
    # Background Refresher
    "OAUTH_REFRESH_INTERVAL",
    # Batch Persistence
    "USAGE_BATCH_PERSISTENCE",
    # DNS Resolver
    "HTTP_DNS_RESOLVER",
    # SSL
    "SSL_FORCE_TLS12",
    "HTTP_SSL_VERIFY_HOSTS",
    # LiteLLM Patches
    "PATCH_LITELLM_FINISH_REASON",
    "SUPPRESS_LITELLM_SERIALIZATION_WARNINGS",
    # HTTP Client Misc
    "HTTP2_ENABLED",
    # Env helpers
    "env_bool",
    "env_float",
    "env_int",
]
