# SPDX-License-Identifier: LGPL-3.0-only
# Copyright (c) 2026 ShmidtS

"""
Configuration module for the rotator library.

Exports centralized defaults used via the package path.
"""

from .defaults import (
    CIRCUIT_BREAKER_PROVIDER_OVERRIDES,
    COOLDOWN_AUTH_ERROR,
    COOLDOWN_BACKOFF_MAX,
    COOLDOWN_BACKOFF_TIERS,
    COOLDOWN_RATE_LIMIT_DEFAULT,
    COOLDOWN_TRANSIENT_ERROR,
    DEFAULT_CUSTOM_CAP_COOLDOWN_MODE,
    DEFAULT_CUSTOM_CAP_COOLDOWN_VALUE,
    DEFAULT_EXHAUSTION_COOLDOWN_THRESHOLD,
    DEFAULT_FAIR_CYCLE_CROSS_TIER,
    DEFAULT_FAIR_CYCLE_DURATION,
    DEFAULT_FAIR_CYCLE_ENABLED,
    DEFAULT_FAIR_CYCLE_TRACKING_MODE,
    DEFAULT_GLOBAL_TIMEOUT,
    DEFAULT_MAX_RETRIES,
    DEFAULT_ROTATION_MODE,
    DEFAULT_ROTATION_TOLERANCE,
    DEFAULT_SEQUENTIAL_FALLBACK_MULTIPLIER,
    DEFAULT_TIER_PRIORITY,
    env_bool,
    env_float,
    env_int,
)

__all__ = [
    "CIRCUIT_BREAKER_PROVIDER_OVERRIDES",
    "COOLDOWN_AUTH_ERROR",
    "COOLDOWN_BACKOFF_MAX",
    "COOLDOWN_BACKOFF_TIERS",
    "COOLDOWN_RATE_LIMIT_DEFAULT",
    "COOLDOWN_TRANSIENT_ERROR",
    "DEFAULT_CUSTOM_CAP_COOLDOWN_MODE",
    "DEFAULT_CUSTOM_CAP_COOLDOWN_VALUE",
    "DEFAULT_EXHAUSTION_COOLDOWN_THRESHOLD",
    "DEFAULT_FAIR_CYCLE_CROSS_TIER",
    "DEFAULT_FAIR_CYCLE_DURATION",
    "DEFAULT_FAIR_CYCLE_ENABLED",
    "DEFAULT_FAIR_CYCLE_TRACKING_MODE",
    "DEFAULT_GLOBAL_TIMEOUT",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_ROTATION_MODE",
    "DEFAULT_ROTATION_TOLERANCE",
    "DEFAULT_SEQUENTIAL_FALLBACK_MULTIPLIER",
    "DEFAULT_TIER_PRIORITY",
    "env_bool",
    "env_float",
    "env_int",
]
